### ISSUE TITLE
Only dragging works

### ISSUE THREAD

**Issue by VonKavalier** [pRizz/Easy-File-Encryptor-Decryptor#1]
This project seems unmaintained, but since it appears on Yunohost I'm taking my chance.

---

I don't know why, but if I choose a file from the explorer, it seems to think that no file has been provided.
Otherwise, if I drag it, the form works as intended.

This is happening both when encrypting and decrypting a file.

**Comment by pRizz** [comment]
Thank you for pointing this out 👍
